### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by mattallty** [etiennecrb/poker-hud#1]
Hi there,

Just a quick question: is it possible to run this on Mac OS ?
Or did you find some limitations regarding electron on Mac ?

thanks
Matt

**Comment by etiennecrb** [comment]
Unfortunately it's not working on Mac. I don't know why, I sent a specific built once to a Mac user who was willing to try, he just told me it was not starting up..

**Comment by TrollKentWolf** [comment]
Hello, it's not working, where is exe file?
